import express from 'express';
import { createServer } from 'node:http';
import { Server } from 'socket.io';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
const app=express(), httpServer=createServer(app), io=new Server(httpServer), rooms=new Map();
const __dirname=path.dirname(fileURLToPath(import.meta.url));
const PEOPLE=['Checho','Wuen','Dieguín','David','Estiben','Juanca','Bray','Alejo','Jaider'];
const WORDS=['deploy','reunión','bug','roadmap','producción','café','ticket','rollback','métrica','cliente','deadline','daily','incidente','equipo','viernes','release','soporte','sprint','documentación','dependencia','pipeline','vacaciones','chat','pruebas','backlog','liderazgo','código','revisión','alarma','aprobación','servidor','prioridad','diseño','caos','éxito'];
function shuffle(a){return [...a].sort(()=>Math.random()-.5)}
function state(r){return {id:r.id,hostId:r.hostId,started:r.started,players:[...r.players.values()].map(p=>({...p,words:undefined})),teams:r.teams,captainIds:r.captainIds,board:r.started?r.board.map(c=>({word:c.word,team:c.revealed?c.team:null,revealed:c.revealed})):null,turnTeam:r.turnTeam,clue:r.clue,log:r.log.slice(-8)}}
function room(id){if(!rooms.has(id))rooms.set(id,{id,hostId:null,started:false,players:new Map(),teams:{red:[],blue:[]},captainIds:{red:null,blue:null},board:[],turnTeam:'red',clue:null,log:[]});return rooms.get(id)}
function send(r){io.to(r.id).emit('state',state(r))}
function start(r){const ps=[...r.players.values()];r.teams={red:[],blue:[]};shuffle(ps).forEach((p,i)=>{p.team=i%2?'blue':'red';r.teams[p.team].push(p.id)});for(const t of ['red','blue'])r.captainIds[t]=r.teams[t][Math.floor(Math.random()*r.teams[t].length)];const chosen=shuffle(WORDS).slice(0,25);const roles=shuffle(['red','red','red','red','red','red','red','blue','blue','blue','blue','blue','blue','blue','neutral','neutral','neutral','neutral','neutral','neutral','neutral','neutral','neutral','neutral','assassin']);r.board=chosen.map((word,i)=>({word,team:roles[i],revealed:false}));r.started=true;r.turnTeam='red';r.log.push('🎲 Equipos y capitanes sorteados. Empieza el equipo rojo.');}
app.use(express.static(path.join(__dirname,'public')));app.get('/health',(_,res)=>res.json({ok:true,rooms:rooms.size}));
io.on('connection',s=>{s.on('join',({roomId,name})=>{const r=room(String(roomId||'sala').toLowerCase().replace(/[^a-z0-9-]/g,'').slice(0,32)||'sala');const n=String(name||'').trim().slice(0,20);if(!n)return s.emit('errorMessage','Escribe tu nombre.');if(r.started||r.players.size>=10)return s.emit('errorMessage','La sala ya está llena o comenzó.');if(!r.hostId&&n.toLowerCase()!=='checho')return s.emit('errorMessage','Checho debe crear la sala.');if(!r.hostId)r.hostId=s.id;r.players.set(s.id,{id:s.id,name:n,team:null});s.join(r.id);s.data.roomId=r.id;r.log.push(`${n} entró a la sala.`);send(r)});s.on('addBots',()=>{const r=rooms.get(s.data.roomId);if(!r||r.hostId!==s.id||r.started||r.players.size!==1)return;PEOPLE.filter(n=>n!=='Checho').forEach((n,i)=>r.players.set(`bot-${i}`,{id:`bot-${i}`,name:`${n} (bot)`,bot:true,team:null}));r.log.push('🤖 Se agregaron 8 bots.');send(r)});s.on('shuffleTeams',()=>{const r=rooms.get(s.data.roomId);if(!r||r.hostId!==s.id||r.players.size<2||r.started)return;start(r);r.started=false;r.board=[];r.log.push('🔀 Participantes y capitanes listos. Pulsa iniciar.');send(r)});s.on('start',()=>{const r=rooms.get(s.data.roomId);if(!r||r.hostId!==s.id||r.players.size<2||r.started)return;start(r);send(r)});s.on('clue',({text,count})=>{const r=rooms.get(s.data.roomId),p=r&&r.players.get(s.id);if(!r||!p||r.captainIds[r.turnTeam]!==s.id||!String(text).trim())return;r.clue={text:String(text).slice(0,30),count:Math.max(1,Math.min(9,Number(count)||1))};r.log.push(`🗣️ ${p.name}: ${r.clue.text} ${r.clue.count}`);send(r)});s.on('guess',({index})=>{const r=rooms.get(s.data.roomId),p=r&&r.players.get(s.id),c=r&&r.board[index];if(!r||!p||!c||!r.clue||p.team!==r.turnTeam||c.revealed)return;c.revealed=true;r.log.push(`${p.name} reveló «${c.word}».`);if(c.team==='assassin'||c.team!==r.turnTeam)r.turnTeam=r.turnTeam==='red'?'blue':'red';if(r.board.filter(x=>x.team===r.turnTeam&&!x.revealed).length===0)r.log.push(`🏆 Gana el equipo ${r.turnTeam}.`);send(r)});s.on('endTurn',()=>{const r=rooms.get(s.data.roomId);if(r){r.turnTeam=r.turnTeam==='red'?'blue':'red';r.clue=null;send(r)}});});
httpServer.listen(process.env.PORT||3000,()=>console.log('Codenames Off Topic listening'));
